### ISSUE TITLE
Update to PySide6

### ISSUE THREAD

**Issue by krihal** [tumpaproject/tumpa#48]
There might be reasons I'm not aware of to stay at PySide2, but with PySide6 Tumpa would run natively on newer MacBooks for example, which would save users the hassle using Rosetta for x86 emulation. After all there are quite a few people at SUNET and other organizations which are using MacBooks.

Here is a PR for updating to PySide6: https://github.com/kushaldas/tumpa/pull/47

**Comment by SaptakS** [comment]
We were planning to update to PySide6, but I think @kushaldas needs to check some packaging related stuff to ensure everything still works properly. Thanks for the PR!!! We will get to it soon.
